functions:
  - name: "volume"
    target: "总体"
  - name: "volume"
    target: "渠道"
  - name: "attitude"
    target: "总体"
  - name: "attitude"
    target: "渠道"
  - name: "trends"
    target: "总体"
  - name: "trends"
    target: "渠道"
  - name: "keywords"
    target: "总体"
  - name: "keywords"
    target: "渠道"
  - name: "theme"
    target: "总体"
  - name: "theme"
    target: "渠道"
  - name: "geography"
    target: "总体"
  - name: "geography"
    target: "渠道"
  - name: "publishers"
    target: "总体"
  - name: "publishers"
    target: "渠道"
  - name: "highlights"
    target: "总体"
  - name: "highlights"
    target: "渠道"
